### PR TITLE
f/typescript port

### LINKED ISSUE #15: Typescript defs
would you consider adding typescript defs? Or perhaps porting the project?

P. S. Happy to help out if it aligns with the goals of this project.

### PR DESCRIPTION
**Pull request by creatorrr**
- feat: Typescript port
- feat: Version bump and add prepare script

Closes #15

### CODE REVIEW

**Comment by nicholascelestin** [comment]
Thanks so much, this is awesome! I've been doing some reading up on TS, and I'm looking this over, wrapping my head around it, and will propose some edits for you to look at in the next couple of days.

**Comment by creatorrr** [comment]
Feel free to add any comments where you might need clarifications etc. I'd be happy to answer. :)

**Comment by creatorrr** [comment]
Also, btw I couldn't get the browser-e2e tests to work just yet so might need some help on that one

**Comment by nicholascelestin** [comment]
Ugh, stuff is breaking in the CI tests and I'm not yet sure why, so working on that.

Basically, I fiddled about a bit with the types and interfaces; e.g. using interfaces to avoid redeclaring fields on the replicate class, making both the prediction output and input explicit. And I injected prettier into the repo to simplify the question of how to format stuff. I also made it so that the replicate.js file is still included in the repo, for people who just use vanilla JS.

Gotta run for the moment, but may be on later tonight. Thanks again for your contribution-- this saved a ton of time and was a great educational experience for me! Let me know what you think of my edits, and I'll work on the CI tests.

**Comment by creatorrr** [comment]
Looks good! Were you able to get the CI tests working?

**Comment by nicholascelestin** [comment]
My github foo is not strong, but I was able to chip away and get it working eventually. Merged now, thanks again!

**Pull request merged**
